### ISSUE TITLE
Device Configuration pane doesn't refresh after the diagram has been updated

### ISSUE THREAD

**Issue by nuntipat** [InGarage/MakerPlayGround#9]
### Description
The actual device in the device configuration pane may not be grey out correctly when the actual device was selected before using the device in the diagram.

### Step to reproduce
1. Select a controller such as the Arduino UNO and add a Generic LDR to the project
2. Add the light sensor (Light1) to the condition and enable compare by Intensity
3. The actual device of Light1 (the generic LDR) should be grey out as it doesn't support the value used (intensity)

**Comment by jetstreamc** [comment]
Already fixed in 0908685c8c48eba6f28bfce4f5e96a5177360130
